"""Comprehensive export service for Markdown, HTML, BibTeX, and Microsoft Word (.docx)."""

import io
import re
from typing import Dict, Any, List, Optional
from datetime import datetime
from urllib.parse import urlparse

import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn


def generate_bibtex(title: str, sources: List[Dict[str, Any]]) -> str:
    """Generate clean, valid BibTeX entries for all cited sources."""
    entries = []
    
    for idx, src in enumerate(sources, start=1):
        url = src.get("url", "")
        src_title = src.get("title", f"Reference {idx}").replace("{", "").replace("}", "")
        domain = ""
        if url:
            try:
                domain = urlparse(url).netloc.replace("www.", "")
            except Exception:
                domain = "web"
        
        # Determine year
        year = str(datetime.now().year)
        
        # Clean citekey e.g. vance2026deep or domain2026_1
        clean_domain = re.sub(r'[^a-zA-Z0-9]', '', domain) or "source"
        cite_key = f"{clean_domain}_{year}_{idx}"
        
        entry = (
            f"@online{{{cite_key},\n"
            f"  title = {{{{{src_title}}}}},\n"
            f"  year = {{{year}}},\n"
            f"  url = {{{url}}},\n"
            f"  urldate = {{{datetime.now().strftime('%Y-%m-%d')}}},\n"
            f"  organization = {{{domain or 'Deep Research Assistant'}}}\n"
            f"}}"
        )
        entries.append(entry)
    
    header = (
        f"% BibTeX Bibliography for: {title}\n"
        f"% Generated by The Journal of Autonomous Inquiry / Deep Research Assistant\n"
        f"% Total Citations: {len(sources)}\n"
        f"% Generated on: {datetime.now().isoformat()}\n\n"
    )
    return header + "\n\n".join(entries) + "\n"


def generate_docx_document(title: str, markdown_content: str, sources: List[Dict[str, Any]]) -> bytes:
    """Generate a professionally styled Microsoft Word (.docx) document."""
    doc = docx.Document()
    
    # Page setup: Standard Letter, 1 inch margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        
    # Color palette
    COLOR_FOREST = RGBColor(0x2A, 0x47, 0x36)  # #2A4736
    COLOR_INK = RGBColor(0x1C, 0x1B, 0x1A)     # #1C1B1A
    COLOR_MUTED = RGBColor(0x70, 0x6E, 0x6B)   # #706E6B
    
    # Header Banner
    header_p = doc.add_paragraph()
    header_run = header_p.add_run("THE JOURNAL OF AUTONOMOUS INQUIRY · MONOGRAPH")
    header_run.font.name = "Georgia"
    header_run.font.size = Pt(8.5)
    header_run.font.bold = True
    header_run.font.color.rgb = COLOR_FOREST
    header_p.paragraph_format.space_after = Pt(4)
    
    # Monograph Title
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(title)
    title_run.font.name = "Georgia"
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = COLOR_INK
    title_p.paragraph_format.space_after = Pt(8)
    
    # Subhead / Meta
    meta_p = doc.add_paragraph()
    date_str = datetime.now().strftime("%B %d, %Y")
    meta_run = meta_p.add_run(f"Autonomous Multi-Agent Investigation · {date_str} · {len(sources)} Verified Citations")
    meta_run.font.name = "Calibri"
    meta_run.font.size = Pt(9.5)
    meta_run.font.italic = True
    meta_run.font.color.rgb = COLOR_MUTED
    meta_p.paragraph_format.space_after = Pt(20)
    
    # Parse Markdown lines
    lines = markdown_content.split("\n")
    in_code_block = False
    
    for raw_line in lines:
        line = raw_line.rstrip()
        
        if line.startswith("```"):
            in_code_block = not in_code_block
            continue
            
        if in_code_block:
            p = doc.add_paragraph()
            r = p.add_run(line)
            r.font.name = "Consolas"
            r.font.size = Pt(9)
            r.font.color.rgb = COLOR_INK
            p.paragraph_format.left_indent = Inches(0.3)
            p.paragraph_format.space_after = Pt(2)
            continue
            
        if not line:
            continue
            
        if line.startswith("# "):
            # Heading 1
            h = doc.add_paragraph()
            r = h.add_run(line[2:].strip())
            r.font.name = "Georgia"
            r.font.size = Pt(16)
            r.font.bold = True
            r.font.color.rgb = COLOR_FOREST
            h.paragraph_format.space_before = Pt(16)
            h.paragraph_format.space_after = Pt(6)
        elif line.startswith("## "):
            # Heading 2
            h = doc.add_paragraph()
            r = h.add_run(line[3:].strip())
            r.font.name = "Georgia"
            r.font.size = Pt(13)
            r.font.bold = True
            r.font.color.rgb = COLOR_INK
            h.paragraph_format.space_before = Pt(12)
            h.paragraph_format.space_after = Pt(4)
        elif line.startswith("### "):
            # Heading 3
            h = doc.add_paragraph()
            r = h.add_run(line[4:].strip())
            r.font.name = "Georgia"
            r.font.size = Pt(11)
            r.font.bold = True
            r.font.color.rgb = COLOR_INK
            h.paragraph_format.space_before = Pt(8)
            h.paragraph_format.space_after = Pt(2)
        elif line.startswith("- ") or line.startswith("* "):
            # Bullet item
            p = doc.add_paragraph(style="List Bullet")
            item_text = line[2:].strip()
            _format_inlines_to_paragraph(p, item_text, COLOR_INK, COLOR_FOREST)
            p.paragraph_format.space_after = Pt(2)
        elif line.startswith("> "):
            # Callout blockquote
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.4)
            r = p.add_run("“ " + line[2:].strip() + " ”")
            r.font.name = "Georgia"
            r.font.size = Pt(10)
            r.font.italic = True
            r.font.color.rgb = COLOR_FOREST
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(6)
        else:
            # Body paragraph
            p = doc.add_paragraph()
            _format_inlines_to_paragraph(p, line, COLOR_INK, COLOR_FOREST)
            p.paragraph_format.line_spacing = 1.15
            p.paragraph_format.space_after = Pt(6)

    # Footnotes / Sources Section
    if sources:
        doc.add_page_break()
        sec_h = doc.add_paragraph()
        sec_r = sec_h.add_run("Primary Sources & References")
        sec_r.font.name = "Georgia"
        sec_r.font.size = Pt(14)
        sec_r.font.bold = True
        sec_r.font.color.rgb = COLOR_FOREST
        sec_h.paragraph_format.space_before = Pt(10)
        sec_h.paragraph_format.space_after = Pt(8)
        
        for idx, src in enumerate(sources, start=1):
            src_p = doc.add_paragraph()
            num_r = src_p.add_run(f"[{idx}] ")
            num_r.font.bold = True
            num_r.font.name = "Calibri"
            num_r.font.size = Pt(9.5)
            num_r.font.color.rgb = COLOR_FOREST
            
            title_r = src_p.add_run(src.get("title", "Untitled Source") + ". ")
            title_r.font.name = "Calibri"
            title_r.font.size = Pt(9.5)
            title_r.font.color.rgb = COLOR_INK
            
            url_r = src_p.add_run(src.get("url", ""))
            url_r.font.name = "Calibri"
            url_r.font.size = Pt(8.5)
            url_r.font.color.rgb = COLOR_MUTED
            
            src_p.paragraph_format.space_after = Pt(3)

    target_stream = io.BytesIO()
    doc.save(target_stream)
    return target_stream.getvalue()


def _format_inlines_to_paragraph(p, text: str, default_color: RGBColor, link_color: RGBColor):
    """Helper to convert markdown bold, italic, and inline citation links into run elements."""
    # Pattern to match bold **text** or citations [1]
    tokens = re.split(r'(\*\*.*?\*\*|\[\d+\])', text)
    for token in tokens:
        if not token:
            continue
        if token.startswith("**") and token.endswith("**"):
            bold_run = p.add_run(token[2:-2])
            bold_run.font.name = "Calibri"
            bold_run.font.size = Pt(10.5)
            bold_run.font.bold = True
            bold_run.font.color.rgb = default_color
        elif re.match(r'^\[\d+\]$', token):
            cite_run = p.add_run(token)
            cite_run.font.name = "Calibri"
            cite_run.font.size = Pt(8.5)
            cite_run.font.bold = True
            cite_run.font.superscript = True
            cite_run.font.color.rgb = link_color
        else:
            norm_run = p.add_run(token)
            norm_run.font.name = "Calibri"
            norm_run.font.size = Pt(10.5)
            norm_run.font.color.rgb = default_color


def generate_html_document(title: str, markdown_content: str, metadata: Optional[Dict[str, Any]] = None) -> str:
    """Generate standalone styled HTML document from markdown research report with editorial print styling."""
    lines = markdown_content.split("\n")
    formatted_lines = []
    in_code_block = False
    in_ul = False
    
    for line in lines:
        if line.startswith("```"):
            in_code_block = not in_code_block
            formatted_lines.append("<pre class='bg-gray-100 p-4 rounded text-xs font-mono overflow-x-auto'><code>" if in_code_block else "</code></pre>")
            continue
        
        if in_code_block:
            formatted_lines.append(line.replace("<", "&lt;").replace(">", "&gt;"))
            continue
        
        if line.startswith("# "):
            formatted_lines.append(f"<h1 class='text-2xl sm:text-3xl font-serif font-bold mt-8 mb-4 text-[#1C1B1A] border-b border-[#DFD9CF] pb-2'>{line[2:]}</h1>")
        elif line.startswith("## "):
            formatted_lines.append(f"<h2 class='text-xl sm:text-2xl font-serif font-bold mt-6 mb-3 text-[#2A4736] border-b border-[#DFD9CF] pb-1.5'>{line[3:]}</h2>")
        elif line.startswith("### "):
            formatted_lines.append(f"<h3 class='text-lg font-serif font-bold mt-4 mb-2 text-[#1C1B1A]'>{line[4:]}</h3>")
        elif line.startswith("- ") or line.startswith("* "):
            if not in_ul:
                formatted_lines.append("<ul class='list-disc pl-6 space-y-1 mb-4 text-[#1C1B1A]'>")
                in_ul = True
            item_text = line[2:]
            item_text = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2" target="_blank" class="text-[#2A4736] underline">\1</a>', item_text)
            item_text = re.sub(r'\[(\d+)\]', r'<sup class="text-[#2A4736] font-bold">[\1]</sup>', item_text)
            formatted_lines.append(f"<li>{item_text}</li>")
        elif line.strip() == "":
            if in_ul:
                formatted_lines.append("</ul>")
                in_ul = False
            formatted_lines.append("<p class='mb-2'></p>")
        else:
            if in_ul:
                formatted_lines.append("</ul>")
                in_ul = False
            p_text = line
            p_text = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', p_text)
            p_text = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2" target="_blank" class="text-[#2A4736] underline">\1</a>', p_text)
            p_text = re.sub(r'\[(\d+)\]', r'<sup class="text-[#2A4736] font-bold">[\1]</sup>', p_text)
            formatted_lines.append(f"<p class='leading-relaxed text-[#1C1B1A] mb-3.5 font-serif'>{p_text}</p>")
            
    if in_ul:
        formatted_lines.append("</ul>")
        
    content_html = "\n".join(formatted_lines)
    date_str = datetime.now().strftime("%B %d, %Y")
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} · The Journal of Autonomous Inquiry</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Lora:ital,wght@0,400;0,600;1,400&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
    <style>
        body {{ font-family: 'Lora', serif; background-color: #F9F6F0; color: #1C1B1A; }}
        h1, h2, h3, h4 {{ font-family: 'Playfair Display', serif; }}
        .font-mono {{ font-family: 'JetBrains Mono', monospace; }}
        @media print {{
            body {{ background-color: #FFFFFF !important; }}
            .no-print {{ display: none !important; }}
            .page-break {{ page-break-before: always; }}
        }}
    </style>
</head>
<body class="py-10 px-4 sm:px-8">
    <div class="max-w-4xl mx-auto bg-[#F1EDE4] p-8 sm:p-14 shadow-sm border border-[#DFD9CF]">
        <div class="border-b border-[#DFD9CF] pb-6 mb-8 flex justify-between items-center">
            <div>
                <span class="text-xs font-mono uppercase tracking-widest text-[#2A4736] bg-[#F9F6F0] border border-[#DFD9CF] px-3 py-1 rounded-[2px] font-bold">The Journal of Autonomous Inquiry</span>
                <p class="text-xs text-[#706E6B] font-mono mt-2">Investigative Monograph · {date_str}</p>
            </div>
            <button onclick="window.print()" class="no-print bg-[#2A4736] hover:bg-[#1E3326] text-[#F9F6F0] text-xs font-serif font-bold px-4 py-2 rounded-[2px] transition">Print / Save PDF</button>
        </div>
        <div class="prose max-w-none">
            {content_html}
        </div>
    </div>
</body>
</html>
"""
